name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag telegram-bot:$(date +%s)
    - uses: actions/checkout@v3
    - name: The job has succeeded
      if: ${{ always() }}
